version: '3.4'

services:
  sannel.house.web:
    image: ${DOCKER_REGISTRY}sannelhouseweb
    build:
      context: .
      dockerfile: src\Sannel.House.Web\Dockerfile
    ports:
      - "80:80"
      - "443:443"
