version: '3.4'

services:
  sannel.house.web:
    image: ${DOCKER_REGISTRY}house.web:dev
    build:
      context: .
      dockerfile: src\Sannel.House.Web\Dockerfile
    ports:
      - "80"
      - "443"
