version: '3.5'

services:
  web:
    image: sannel/house.web:dev
    build:
      context: .
      dockerfile: src/Sannel.House.Web/Dockerfile
#    volumes:
#      - "d:/Data/dev/logs:c:/app/logs"
#      - "d:/Data/dev/config:c:/app/config"
    environment:
      - DELAY_START=30000
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sql
    networks:
      - house_web

  sql:
    image: microsoft/mssql-server-windows-express
    environment:
      - ACCEPT_EULA=no
      - sa_password=@password1
#      - "attach_dbs=[{'dbName':'devHouse','dbFiles':['C:\\\\data\\\\devHouse.mdf','C:\\\\data\\\\devHouse_log.ldf']}]"
#    volumes:
#      - "D:/Data/dev:c:/Data"
    networks:
      - house_web

networks:
  house_web:
    driver: nat