version: "2.4"

services:
  mongo:
    image: mongo:3.6.1

  web:
    image: sannel/house.web:dev-linux
    build:
      dockerfile: src/Sannel.House.Web/Dockerfile.linux

  sql:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=@Password1

networks:
  house_web:
    driver: bridge