version: "2.4"

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Sannel.House.Web.sln && dotnet publish ./Sannel.House.Web.sln -c Release -o ./obj/Docker/publish"
